// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const attachUserWallet = `-- name: AttachUserWallet :execrows
INSERT INTO user_wallets (user_id, privy_wallet_id, address, created_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
`

type AttachUserWalletParams struct {
	UserID        uuid.UUID
	PrivyWalletID string
	Address       string
	CreatedAt     time.Time
}

func (q *Queries) AttachUserWallet(ctx context.Context, arg AttachUserWalletParams) (int64, error) {
	result, err := q.db.Exec(ctx, attachUserWallet,
		arg.UserID,
		arg.PrivyWalletID,
		arg.Address,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createUser = `-- name: CreateUser :execrows
INSERT INTO users (id, privy_user_id, login_provider, auth_state_changed_at, created_at, updated_at)
VALUES ($1, $2, $3, $4, $4, $4)
ON CONFLICT (privy_user_id) DO NOTHING
`

type CreateUserParams struct {
	ID            uuid.UUID
	PrivyUserID   string
	LoginProvider string
	Now           time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.PrivyUserID,
		arg.LoginProvider,
		arg.Now,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUser = `-- name: DeleteUser :execrows
UPDATE users SET account_status = 'deleted', deleted_at = $1::timestamptz, updated_at = $1,
  email = NULL, phone_e164 = NULL, phone_hash = NULL, phone_verified_at = NULL,
  x_user_id = NULL, x_username = NULL, x_linked_at = NULL, photo_url = NULL, display_name = ''
WHERE id = $2 AND account_status = $3
`

type DeleteUserParams struct {
	Now      time.Time
	ID       uuid.UUID
	Expected string
}

func (q *Queries) DeleteUser(ctx context.Context, arg DeleteUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, arg.Now, arg.ID, arg.Expected)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findUserByID = `-- name: FindUserByID :one
SELECT u.id, u.privy_user_id, u.handle, u.auth_state, u.account_status, u.phone_e164, u.x_user_id, u.x_username,
  w.privy_wallet_id, w.address
FROM users u
LEFT JOIN user_wallets w ON w.user_id = u.id
WHERE u.id = $1 AND u.deleted_at IS NULL
`

type FindUserByIDRow struct {
	ID            uuid.UUID
	PrivyUserID   string
	Handle        pgtype.Text
	AuthState     string
	AccountStatus string
	PhoneE164     pgtype.Text
	XUserID       pgtype.Text
	XUsername     pgtype.Text
	PrivyWalletID pgtype.Text
	Address       pgtype.Text
}

func (q *Queries) FindUserByID(ctx context.Context, id uuid.UUID) (FindUserByIDRow, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i FindUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.PrivyUserID,
		&i.Handle,
		&i.AuthState,
		&i.AccountStatus,
		&i.PhoneE164,
		&i.XUserID,
		&i.XUsername,
		&i.PrivyWalletID,
		&i.Address,
	)
	return i, err
}

const findUserByPrivyUserID = `-- name: FindUserByPrivyUserID :one
SELECT u.id, u.privy_user_id, u.handle, u.auth_state, u.account_status, u.phone_e164, u.x_user_id, u.x_username,
  w.privy_wallet_id, w.address
FROM users u
LEFT JOIN user_wallets w ON w.user_id = u.id
WHERE u.privy_user_id = $1
`

type FindUserByPrivyUserIDRow struct {
	ID            uuid.UUID
	PrivyUserID   string
	Handle        pgtype.Text
	AuthState     string
	AccountStatus string
	PhoneE164     pgtype.Text
	XUserID       pgtype.Text
	XUsername     pgtype.Text
	PrivyWalletID pgtype.Text
	Address       pgtype.Text
}

func (q *Queries) FindUserByPrivyUserID(ctx context.Context, privyUserID string) (FindUserByPrivyUserIDRow, error) {
	row := q.db.QueryRow(ctx, findUserByPrivyUserID, privyUserID)
	var i FindUserByPrivyUserIDRow
	err := row.Scan(
		&i.ID,
		&i.PrivyUserID,
		&i.Handle,
		&i.AuthState,
		&i.AccountStatus,
		&i.PhoneE164,
		&i.XUserID,
		&i.XUsername,
		&i.PrivyWalletID,
		&i.Address,
	)
	return i, err
}

const insertDevUser = `-- name: InsertDevUser :exec
INSERT INTO users (
  id, privy_user_id, login_provider, handle, display_name, auth_state_changed_at, created_at, updated_at
) VALUES (
  $1, $2, 'email', $3, $4,
  $5, $5, $5
)
`

type InsertDevUserParams struct {
	ID          uuid.UUID
	PrivyUserID string
	Handle      pgtype.Text
	DisplayName string
	Now         time.Time
}

func (q *Queries) InsertDevUser(ctx context.Context, arg InsertDevUserParams) error {
	_, err := q.db.Exec(ctx, insertDevUser,
		arg.ID,
		arg.PrivyUserID,
		arg.Handle,
		arg.DisplayName,
		arg.Now,
	)
	return err
}

const linksHeldByOthers = `-- name: LinksHeldByOthers :one
SELECT
  EXISTS (
    SELECT 1 FROM users o
    WHERE $1::bytea IS NOT NULL
      AND o.phone_hash = $1::bytea
      AND o.id <> $2
  ) AS phone,
  EXISTS (
    SELECT 1 FROM users o
    WHERE $3::text IS NOT NULL
      AND o.x_user_id = $3::text
      AND o.id <> $2
  ) AS x
`

type LinksHeldByOthersParams struct {
	PhoneHash []byte
	ID        uuid.UUID
	XUserID   pgtype.Text
}

type LinksHeldByOthersRow struct {
	Phone bool
	X     bool
}

func (q *Queries) LinksHeldByOthers(ctx context.Context, arg LinksHeldByOthersParams) (LinksHeldByOthersRow, error) {
	row := q.db.QueryRow(ctx, linksHeldByOthers, arg.PhoneHash, arg.ID, arg.XUserID)
	var i LinksHeldByOthersRow
	err := row.Scan(&i.Phone, &i.X)
	return i, err
}

const lockUserByID = `-- name: LockUserByID :one
SELECT u.id, u.privy_user_id, u.handle, u.auth_state, u.account_status, u.phone_e164, u.x_user_id, u.x_username,
  w.privy_wallet_id, w.address
FROM users u
LEFT JOIN user_wallets w ON w.user_id = u.id
WHERE u.id = $1 AND u.deleted_at IS NULL
FOR UPDATE OF u
`

type LockUserByIDRow struct {
	ID            uuid.UUID
	PrivyUserID   string
	Handle        pgtype.Text
	AuthState     string
	AccountStatus string
	PhoneE164     pgtype.Text
	XUserID       pgtype.Text
	XUsername     pgtype.Text
	PrivyWalletID pgtype.Text
	Address       pgtype.Text
}

func (q *Queries) LockUserByID(ctx context.Context, id uuid.UUID) (LockUserByIDRow, error) {
	row := q.db.QueryRow(ctx, lockUserByID, id)
	var i LockUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.PrivyUserID,
		&i.Handle,
		&i.AuthState,
		&i.AccountStatus,
		&i.PhoneE164,
		&i.XUserID,
		&i.XUsername,
		&i.PrivyWalletID,
		&i.Address,
	)
	return i, err
}

const lockUserByPrivyUserID = `-- name: LockUserByPrivyUserID :one
SELECT u.id, u.privy_user_id, u.handle, u.auth_state, u.account_status, u.phone_e164, u.x_user_id, u.x_username,
  w.privy_wallet_id, w.address
FROM users u
LEFT JOIN user_wallets w ON w.user_id = u.id
WHERE u.privy_user_id = $1
FOR UPDATE OF u
`

type LockUserByPrivyUserIDRow struct {
	ID            uuid.UUID
	PrivyUserID   string
	Handle        pgtype.Text
	AuthState     string
	AccountStatus string
	PhoneE164     pgtype.Text
	XUserID       pgtype.Text
	XUsername     pgtype.Text
	PrivyWalletID pgtype.Text
	Address       pgtype.Text
}

func (q *Queries) LockUserByPrivyUserID(ctx context.Context, privyUserID string) (LockUserByPrivyUserIDRow, error) {
	row := q.db.QueryRow(ctx, lockUserByPrivyUserID, privyUserID)
	var i LockUserByPrivyUserIDRow
	err := row.Scan(
		&i.ID,
		&i.PrivyUserID,
		&i.Handle,
		&i.AuthState,
		&i.AccountStatus,
		&i.PhoneE164,
		&i.XUserID,
		&i.XUsername,
		&i.PrivyWalletID,
		&i.Address,
	)
	return i, err
}

const markPhotoPurged = `-- name: MarkPhotoPurged :execrows
UPDATE users SET photo_purged_at = $1::timestamptz
WHERE id = $2 AND account_status = 'deleted' AND photo_purged_at IS NULL
`

type MarkPhotoPurgedParams struct {
	At time.Time
	ID uuid.UUID
}

func (q *Queries) MarkPhotoPurged(ctx context.Context, arg MarkPhotoPurgedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markPhotoPurged, arg.At, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const photoPurgesDue = `-- name: PhotoPurgesDue :many
SELECT id FROM users
WHERE account_status = 'deleted' AND photo_purged_at IS NULL
ORDER BY id
LIMIT $1
`

func (q *Queries) PhotoPurgesDue(ctx context.Context, batch int32) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, photoPurgesDue, batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDisplayName = `-- name: SetDisplayName :execrows
UPDATE users SET display_name = $1, updated_at = $2
WHERE id = $3 AND display_name IS DISTINCT FROM $1
`

type SetDisplayNameParams struct {
	DisplayName string
	Now         time.Time
	ID          uuid.UUID
}

func (q *Queries) SetDisplayName(ctx context.Context, arg SetDisplayNameParams) (int64, error) {
	result, err := q.db.Exec(ctx, setDisplayName, arg.DisplayName, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setFirstDepositAt = `-- name: SetFirstDepositAt :execrows
UPDATE users
SET first_deposit_at = LEAST(COALESCE(first_deposit_at, $1::timestamptz), $1::timestamptz),
    updated_at = $2
WHERE id = $3 AND deleted_at IS NULL
  AND (first_deposit_at IS NULL OR first_deposit_at > $1::timestamptz)
`

type SetFirstDepositAtParams struct {
	DepositedAt time.Time
	Now         time.Time
	ID          uuid.UUID
}

func (q *Queries) SetFirstDepositAt(ctx context.Context, arg SetFirstDepositAtParams) (int64, error) {
	result, err := q.db.Exec(ctx, setFirstDepositAt, arg.DepositedAt, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setPhotoURL = `-- name: SetPhotoURL :execrows
UPDATE users SET photo_url = $1::text, updated_at = $2
WHERE id = $3 AND photo_url IS DISTINCT FROM $1::text
`

type SetPhotoURLParams struct {
	PhotoUrl string
	Now      time.Time
	ID       uuid.UUID
}

func (q *Queries) SetPhotoURL(ctx context.Context, arg SetPhotoURLParams) (int64, error) {
	result, err := q.db.Exec(ctx, setPhotoURL, arg.PhotoUrl, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setUserEmail = `-- name: SetUserEmail :exec
UPDATE users SET email = $1, updated_at = $2
WHERE id = $3 AND email IS DISTINCT FROM $1
`

type SetUserEmailParams struct {
	Email pgtype.Text
	Now   time.Time
	ID    uuid.UUID
}

func (q *Queries) SetUserEmail(ctx context.Context, arg SetUserEmailParams) error {
	_, err := q.db.Exec(ctx, setUserEmail, arg.Email, arg.Now, arg.ID)
	return err
}

const setUserHandle = `-- name: SetUserHandle :execrows
UPDATE users SET handle = $1, handle_changed_at = $2, updated_at = $2
WHERE id = $3 AND deleted_at IS NULL
`

type SetUserHandleParams struct {
	Handle pgtype.Text
	Now    pgtype.Timestamptz
	ID     uuid.UUID
}

func (q *Queries) SetUserHandle(ctx context.Context, arg SetUserHandleParams) (int64, error) {
	result, err := q.db.Exec(ctx, setUserHandle, arg.Handle, arg.Now, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setUserPhone = `-- name: SetUserPhone :exec
UPDATE users SET phone_e164 = $1, phone_hash = $2,
  phone_verified_at = $3, updated_at = $4
WHERE id = $5
`

type SetUserPhoneParams struct {
	PhoneE164  pgtype.Text
	PhoneHash  []byte
	VerifiedAt pgtype.Timestamptz
	Now        time.Time
	ID         uuid.UUID
}

func (q *Queries) SetUserPhone(ctx context.Context, arg SetUserPhoneParams) error {
	_, err := q.db.Exec(ctx, setUserPhone,
		arg.PhoneE164,
		arg.PhoneHash,
		arg.VerifiedAt,
		arg.Now,
		arg.ID,
	)
	return err
}

const setUserX = `-- name: SetUserX :exec
UPDATE users SET x_user_id = $1, x_username = $2,
  x_linked_at = $3, updated_at = $4
WHERE id = $5
`

type SetUserXParams struct {
	XUserID   pgtype.Text
	XUsername pgtype.Text
	LinkedAt  pgtype.Timestamptz
	Now       time.Time
	ID        uuid.UUID
}

func (q *Queries) SetUserX(ctx context.Context, arg SetUserXParams) error {
	_, err := q.db.Exec(ctx, setUserX,
		arg.XUserID,
		arg.XUsername,
		arg.LinkedAt,
		arg.Now,
		arg.ID,
	)
	return err
}

const updateAccountStatus = `-- name: UpdateAccountStatus :execrows
UPDATE users SET account_status = $1, updated_at = $2,
  deleted_at = CASE WHEN $1::text = 'deleted' THEN $2::timestamptz ELSE deleted_at END
WHERE id = $3 AND account_status = $4
`

type UpdateAccountStatusParams struct {
	Next     string
	Now      time.Time
	ID       uuid.UUID
	Expected string
}

func (q *Queries) UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAccountStatus,
		arg.Next,
		arg.Now,
		arg.ID,
		arg.Expected,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAuthState = `-- name: UpdateAuthState :execrows
UPDATE users SET auth_state = $1, auth_state_changed_at = $2, updated_at = $2,
  nudge_count = 0
WHERE id = $3 AND auth_state = $4
`

type UpdateAuthStateParams struct {
	Next     string
	Now      time.Time
	ID       uuid.UUID
	Expected string
}

func (q *Queries) UpdateAuthState(ctx context.Context, arg UpdateAuthStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateAuthState,
		arg.Next,
		arg.Now,
		arg.ID,
		arg.Expected,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
