#!/usr/bin/env bash
# Decrypt repo-root .env.local via dotenvx and materialize iOS Privy config.
# Writes gitignored apps/mobile/Config/Privy.local.xcconfig (xcconfig → Info.plist at build).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/apps/mobile/Config/Privy.local.xcconfig"
ENV_FILE="$ROOT/.env.local"

load_privy_env() {
  if [[ -n "${PRIVY_APP_ID:-}" && -n "${PRIVY_APP_CLIENT_ID:-${PRIVY_AUTH_ID:-}}" ]]; then
    return 0
  fi
  if [[ ! -f "$ENV_FILE" ]]; then
    echo "error: $ENV_FILE missing — set PRIVY_APP_ID and PRIVY_APP_CLIENT_ID with dotenvx." >&2
    exit 1
  fi
  if ! command -v dotenvx >/dev/null 2>&1; then
    echo "error: dotenvx not on PATH. Install: https://dotenvx.com/docs/install" >&2
    exit 1
  fi
  PRIVY_APP_ID="$(cd "$ROOT" && dotenvx get PRIVY_APP_ID -f .env.local 2>/dev/null || true)"
  PRIVY_APP_CLIENT_ID="$(cd "$ROOT" && dotenvx get PRIVY_APP_CLIENT_ID -f .env.local 2>/dev/null || true)"
  PRIVY_AUTH_ID="$(cd "$ROOT" && dotenvx get PRIVY_AUTH_ID -f .env.local 2>/dev/null || true)"
  PRIVY_SMS_LOGIN_ENABLED="$(cd "$ROOT" && dotenvx get PRIVY_SMS_LOGIN_ENABLED -f .env.local 2>/dev/null || true)"
  PRIVY_EMAIL_LOGIN_ENABLED="$(cd "$ROOT" && dotenvx get PRIVY_EMAIL_LOGIN_ENABLED -f .env.local 2>/dev/null || true)"
  PRIVY_AUTHORIZATION_KEY_ID="$(cd "$ROOT" && dotenvx get PRIVY_AUTHORIZATION_KEY_ID -f .env.local 2>/dev/null || true)"
  PRIVY_SMS_LOGIN_ENABLED="${PRIVY_SMS_LOGIN_ENABLED:-true}"
  PRIVY_EMAIL_LOGIN_ENABLED="${PRIVY_EMAIL_LOGIN_ENABLED:-true}"
}

generate_xcconfig() {
  load_privy_env
  local client_id="${PRIVY_APP_CLIENT_ID:-${PRIVY_AUTH_ID:-}}"
  if [[ -z "${PRIVY_APP_ID:-}" || -z "$client_id" ]]; then
    echo "error: PRIVY_APP_ID and PRIVY_APP_CLIENT_ID must be set in .env.local" >&2
    exit 1
  fi

  mkdir -p "$(dirname "$OUT")"
  cat >"$OUT" <<EOF
// Generated by scripts/ensure-ios-privy-config.sh — do not commit.
PRIVY_APP_ID = ${PRIVY_APP_ID}
PRIVY_APP_CLIENT_ID = ${client_id}
PRIVY_SMS_LOGIN_ENABLED = ${PRIVY_SMS_LOGIN_ENABLED:-true}
PRIVY_EMAIL_LOGIN_ENABLED = ${PRIVY_EMAIL_LOGIN_ENABLED:-true}
PRIVY_AUTHORIZATION_KEY_ID = ${PRIVY_AUTHORIZATION_KEY_ID:-}
INFOPLIST_KEY_PRIVY_APP_ID = \$(PRIVY_APP_ID)
INFOPLIST_KEY_PRIVY_APP_CLIENT_ID = \$(PRIVY_APP_CLIENT_ID)
INFOPLIST_KEY_PRIVY_SMS_LOGIN_ENABLED = \$(PRIVY_SMS_LOGIN_ENABLED)
INFOPLIST_KEY_PRIVY_EMAIL_LOGIN_ENABLED = \$(PRIVY_EMAIL_LOGIN_ENABLED)
INFOPLIST_KEY_PRIVY_AUTHORIZATION_KEY_ID = \$(PRIVY_AUTHORIZATION_KEY_ID)
EOF
}

export_launch_env() {
  load_privy_env
  local client_id="${PRIVY_APP_CLIENT_ID:-${PRIVY_AUTH_ID:-}}"
  export PRIVY_APP_ID
  export PRIVY_APP_CLIENT_ID="$client_id"
  export PRIVY_SMS_LOGIN_ENABLED="${PRIVY_SMS_LOGIN_ENABLED:-true}"
  export PRIVY_EMAIL_LOGIN_ENABLED="${PRIVY_EMAIL_LOGIN_ENABLED:-true}"
  export SIMCTL_CHILD_PRIVY_APP_ID="$PRIVY_APP_ID"
  export SIMCTL_CHILD_PRIVY_APP_CLIENT_ID="$client_id"
  export SIMCTL_CHILD_PRIVY_SMS_LOGIN_ENABLED="${PRIVY_SMS_LOGIN_ENABLED:-true}"
  export SIMCTL_CHILD_PRIVY_EMAIL_LOGIN_ENABLED="${PRIVY_EMAIL_LOGIN_ENABLED:-true}"
  export PRIVY_AUTHORIZATION_KEY_ID="${PRIVY_AUTHORIZATION_KEY_ID:-}"
  export SIMCTL_CHILD_PRIVY_AUTHORIZATION_KEY_ID="${PRIVY_AUTHORIZATION_KEY_ID:-}"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  case "${1:-generate}" in
    generate)
      generate_xcconfig
      ;;
    --launch-env)
      generate_xcconfig
      export_launch_env
      ;;
    *)
      echo "usage: ensure-ios-privy-config.sh [generate|--launch-env]" >&2
      exit 1
      ;;
  esac
fi
