#!/usr/bin/env bash
# Decrypt repo-root .env.local via dotenvx and materialize iOS Dynamic config.
# Writes gitignored Dynamic.local.xcconfig + Dynamic.local.Info.plist (merged into app at build).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/apps/mobile/Config/Dynamic.local.xcconfig"
PLIST_OUT="$ROOT/apps/mobile/Config/Dynamic.local.Info.plist"
ENV_FILE="$ROOT/.env.local"

load_dynamic_env() {
  if [[ ! -f "$ENV_FILE" ]]; then
    echo "error: $ENV_FILE missing — set DYNAMIC_ENVIRONMENT_ID with dotenvx." >&2
    exit 1
  fi
  if ! command -v dotenvx >/dev/null 2>&1; then
    echo "error: dotenvx not on PATH. Install: https://dotenvx.com/docs/install" >&2
    exit 1
  fi
  unset DYNAMIC_ENVIRONMENT_ID AUTH_SMS_LOGIN_ENABLED AUTH_EMAIL_LOGIN_ENABLED
  DYNAMIC_ENVIRONMENT_ID="$(cd "$ROOT" && dotenvx get DYNAMIC_ENVIRONMENT_ID -f .env.local 2>/dev/null || true)"
  AUTH_SMS_LOGIN_ENABLED="$(cd "$ROOT" && dotenvx get AUTH_SMS_LOGIN_ENABLED -f .env.local 2>/dev/null || true)"
  AUTH_EMAIL_LOGIN_ENABLED="$(cd "$ROOT" && dotenvx get AUTH_EMAIL_LOGIN_ENABLED -f .env.local 2>/dev/null || true)"
  AUTH_SMS_LOGIN_ENABLED="${AUTH_SMS_LOGIN_ENABLED:-true}"
  AUTH_EMAIL_LOGIN_ENABLED="${AUTH_EMAIL_LOGIN_ENABLED:-true}"
}

require_environment_id() {
  if [[ -z "${DYNAMIC_ENVIRONMENT_ID:-}" ]]; then
    echo "error: DYNAMIC_ENVIRONMENT_ID must be set in .env.local" >&2
    exit 1
  fi
}

generate_info_plist() {
  mkdir -p "$(dirname "$PLIST_OUT")"
  cat >"$PLIST_OUT" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>DYNAMIC_ENVIRONMENT_ID</key>
	<string>${DYNAMIC_ENVIRONMENT_ID}</string>
	<key>AUTH_SMS_LOGIN_ENABLED</key>
	<string>${AUTH_SMS_LOGIN_ENABLED:-true}</string>
	<key>AUTH_EMAIL_LOGIN_ENABLED</key>
	<string>${AUTH_EMAIL_LOGIN_ENABLED:-true}</string>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleURLName</key>
			<string>com.monaco.app</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>monaco</string>
			</array>
		</dict>
	</array>
</dict>
</plist>
EOF
}

generate_xcconfig() {
  load_dynamic_env
  require_environment_id
  mkdir -p "$(dirname "$OUT")"
  cat >"$OUT" <<EOF
// Generated by scripts/ensure-ios-dynamic-config.sh — do not commit.
DYNAMIC_ENVIRONMENT_ID = ${DYNAMIC_ENVIRONMENT_ID}
AUTH_SMS_LOGIN_ENABLED = ${AUTH_SMS_LOGIN_ENABLED:-true}
AUTH_EMAIL_LOGIN_ENABLED = ${AUTH_EMAIL_LOGIN_ENABLED:-true}
EOF
  generate_info_plist
}

export_launch_env() {
  load_dynamic_env
  require_environment_id
  export DYNAMIC_ENVIRONMENT_ID
  export AUTH_SMS_LOGIN_ENABLED="${AUTH_SMS_LOGIN_ENABLED:-true}"
  export AUTH_EMAIL_LOGIN_ENABLED="${AUTH_EMAIL_LOGIN_ENABLED:-true}"
  export SIMCTL_CHILD_DYNAMIC_ENVIRONMENT_ID="$DYNAMIC_ENVIRONMENT_ID"
  export SIMCTL_CHILD_AUTH_SMS_LOGIN_ENABLED="${AUTH_SMS_LOGIN_ENABLED:-true}"
  export SIMCTL_CHILD_AUTH_EMAIL_LOGIN_ENABLED="${AUTH_EMAIL_LOGIN_ENABLED:-true}"
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  case "${1:-generate}" in
    generate)
      generate_xcconfig
      ;;
    --launch-env)
      generate_xcconfig
      export_launch_env
      ;;
    *)
      echo "usage: ensure-ios-dynamic-config.sh [generate|--launch-env]" >&2
      exit 1
      ;;
  esac
fi
