#!/usr/bin/env bash
# Decrypt repo-root .env.local via dotenvx and materialize iOS Privy config.
# Writes gitignored Privy.local.xcconfig + Privy.local.Info.plist (merged into app at build;
# Debug uses Privy.local.Debug.Info.plist, the same keys plus the ATS local-networking
# exception that Release must not carry).
# Also writes gitignored Environment.local.xcconfig with the staging / production API base
# URLs (optional, non-secret) that Config/Monaco.xcconfig resolves MONACO_API_BASE_URL from.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/apps/mobile/Config/Privy.local.xcconfig"
PLIST_OUT="$ROOT/apps/mobile/Config/Privy.local.Info.plist"
DEBUG_PLIST_OUT="$ROOT/apps/mobile/Config/Privy.local.Debug.Info.plist"
ENVIRONMENT_OUT="$ROOT/apps/mobile/Config/Environment.local.xcconfig"
ENV_FILE="$ROOT/.env.local"

load_privy_env() {
  if [[ ! -f "$ENV_FILE" ]]; then
    echo "error: $ENV_FILE missing — set PRIVY_APP_ID and PRIVY_APP_CLIENT_ID with dotenvx." >&2
    exit 1
  fi
  if ! command -v dotenvx >/dev/null 2>&1; then
    echo "error: dotenvx not on PATH. Install: https://dotenvx.com/docs/install" >&2
    exit 1
  fi
  # Always read from .env.local. dotenvx get/run both honor existing shell exports,
  # so clear stale Privy keys before fetching decrypted values.
  unset PRIVY_APP_ID PRIVY_APP_CLIENT_ID PRIVY_AUTH_ID \
    PRIVY_SMS_LOGIN_ENABLED PRIVY_EMAIL_LOGIN_ENABLED PRIVY_AUTHORIZATION_KEY_ID

  PRIVY_APP_ID="$(cd "$ROOT" && dotenvx get PRIVY_APP_ID -f .env.local 2>/dev/null || true)"
  PRIVY_APP_CLIENT_ID="$(cd "$ROOT" && dotenvx get PRIVY_APP_CLIENT_ID -f .env.local 2>/dev/null || true)"
  PRIVY_AUTH_ID="$(cd "$ROOT" && dotenvx get PRIVY_AUTH_ID -f .env.local 2>/dev/null || true)"
  PRIVY_SMS_LOGIN_ENABLED="$(cd "$ROOT" && dotenvx get PRIVY_SMS_LOGIN_ENABLED -f .env.local 2>/dev/null || true)"
  PRIVY_EMAIL_LOGIN_ENABLED="$(cd "$ROOT" && dotenvx get PRIVY_EMAIL_LOGIN_ENABLED -f .env.local 2>/dev/null || true)"
  PRIVY_AUTHORIZATION_KEY_ID="$(cd "$ROOT" && dotenvx get PRIVY_AUTHORIZATION_KEY_ID -f .env.local 2>/dev/null || true)"
  PRIVY_SMS_LOGIN_ENABLED="${PRIVY_SMS_LOGIN_ENABLED:-true}"
  PRIVY_EMAIL_LOGIN_ENABLED="${PRIVY_EMAIL_LOGIN_ENABLED:-true}"
}

resolve_ios_client_id() {
  local client_id="${PRIVY_APP_CLIENT_ID:-}"
  if [[ -z "$client_id" && -n "${PRIVY_AUTH_ID:-}" && "${PRIVY_AUTH_ID}" == client-* ]]; then
    client_id="$PRIVY_AUTH_ID"
  fi
  if [[ -z "${PRIVY_APP_ID:-}" || -z "$client_id" || "$client_id" != client-* ]]; then
    echo "error: PRIVY_APP_ID and PRIVY_APP_CLIENT_ID (client-…) must be set in .env.local" >&2
    exit 1
  fi
  printf '%s' "$client_id"
}

# ATS stays strict everywhere; Debug alone may reach a dev backend over plain http on
# the local network (this Mac's LAN IP / .local name from a device build).
debug_ats_plist_fragment() {
  cat <<'EOF'
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsLocalNetworking</key>
		<true/>
	</dict>
EOF
}

generate_info_plist() {
  local client_id="$1"
  write_info_plist "$PLIST_OUT" "$client_id" ""
  write_info_plist "$DEBUG_PLIST_OUT" "$client_id" "$(debug_ats_plist_fragment)"
}

write_info_plist() {
  local plist_out="$1" client_id="$2" extra_keys="$3"
  mkdir -p "$(dirname "$plist_out")"
  cat >"$plist_out" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>PRIVY_APP_ID</key>
	<string>${PRIVY_APP_ID}</string>
	<key>PRIVY_APP_CLIENT_ID</key>
	<string>${client_id}</string>
	<key>PRIVY_SMS_LOGIN_ENABLED</key>
	<string>${PRIVY_SMS_LOGIN_ENABLED:-true}</string>
	<key>PRIVY_EMAIL_LOGIN_ENABLED</key>
	<string>${PRIVY_EMAIL_LOGIN_ENABLED:-true}</string>
	<key>PRIVY_AUTHORIZATION_KEY_ID</key>
	<string>${PRIVY_AUTHORIZATION_KEY_ID:-}</string>
	<key>MONACO_ENVIRONMENT</key>
	<string>\$(MONACO_ENVIRONMENT)</string>
	<key>MONACO_API_BASE_URL</key>
	<string>\$(MONACO_API_BASE_URL)</string>
${extra_keys}
</dict>
</plist>
EOF
}

# Remote API base URLs are optional, but a value that is set must be https: the app
# refuses anything else in Release, so fail here instead of at launch on a tester's phone.
remote_api_base_url() {
  local key="$1" value
  value="$(cd "$ROOT" && dotenvx get "$key" -f .env.local 2>/dev/null || true)"
  if [[ -n "$value" && "$value" != https://?* ]]; then
    echo "error: $key must be an https:// URL (got: $value)" >&2
    exit 1
  fi
  printf '%s' "$value"
}

# xcconfig reads `//` as the start of a comment; `/$()/` expands back to `//`.
xcconfig_escape_url() {
  local slashes='//' escaped='/$()/'
  printf '%s' "${1//$slashes/$escaped}"
}

generate_environment_xcconfig() {
  local staging production
  staging="$(remote_api_base_url MONACO_STAGING_API_BASE_URL)" || return 1
  production="$(remote_api_base_url MONACO_PRODUCTION_API_BASE_URL)" || return 1

  mkdir -p "$(dirname "$ENVIRONMENT_OUT")"
  cat >"$ENVIRONMENT_OUT" <<EOF
// Generated by scripts/ensure-ios-privy-config.sh — do not commit.
MONACO_STAGING_API_BASE_URL = $(xcconfig_escape_url "$staging")
MONACO_PRODUCTION_API_BASE_URL = $(xcconfig_escape_url "$production")
EOF
}

generate_xcconfig() {
  load_privy_env
  local client_id
  client_id="$(resolve_ios_client_id)"

  mkdir -p "$(dirname "$OUT")"
  cat >"$OUT" <<EOF
// Generated by scripts/ensure-ios-privy-config.sh — do not commit.
PRIVY_APP_ID = ${PRIVY_APP_ID}
PRIVY_APP_CLIENT_ID = ${client_id}
PRIVY_SMS_LOGIN_ENABLED = ${PRIVY_SMS_LOGIN_ENABLED:-true}
PRIVY_EMAIL_LOGIN_ENABLED = ${PRIVY_EMAIL_LOGIN_ENABLED:-true}
PRIVY_AUTHORIZATION_KEY_ID = ${PRIVY_AUTHORIZATION_KEY_ID:-}
EOF
  generate_info_plist "$client_id"
  generate_environment_xcconfig
}

export_launch_env() {
  load_privy_env
  local client_id
  client_id="$(resolve_ios_client_id)"
  export PRIVY_APP_ID
  export PRIVY_APP_CLIENT_ID="$client_id"
  export PRIVY_SMS_LOGIN_ENABLED="${PRIVY_SMS_LOGIN_ENABLED:-true}"
  export PRIVY_EMAIL_LOGIN_ENABLED="${PRIVY_EMAIL_LOGIN_ENABLED:-true}"
  export SIMCTL_CHILD_PRIVY_APP_ID="$PRIVY_APP_ID"
  export SIMCTL_CHILD_PRIVY_APP_CLIENT_ID="$client_id"
  export SIMCTL_CHILD_PRIVY_SMS_LOGIN_ENABLED="${PRIVY_SMS_LOGIN_ENABLED:-true}"
  export SIMCTL_CHILD_PRIVY_EMAIL_LOGIN_ENABLED="${PRIVY_EMAIL_LOGIN_ENABLED:-true}"
  export PRIVY_AUTHORIZATION_KEY_ID="${PRIVY_AUTHORIZATION_KEY_ID:-}"
  export SIMCTL_CHILD_PRIVY_AUTHORIZATION_KEY_ID="${PRIVY_AUTHORIZATION_KEY_ID:-}"
  # Debug-only override: point a simulator at staging or a tunnel without rebuilding,
  # e.g. MONACO_API_BASE_URL=https://… just run mobile. Unset → the build's own URL.
  if [[ -n "${MONACO_API_BASE_URL:-}" ]]; then
    export SIMCTL_CHILD_MONACO_API_BASE_URL="$MONACO_API_BASE_URL"
  fi
  if [[ -n "${MONACO_ENVIRONMENT:-}" ]]; then
    export SIMCTL_CHILD_MONACO_ENVIRONMENT="$MONACO_ENVIRONMENT"
  fi
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  case "${1:-generate}" in
    generate)
      generate_xcconfig
      ;;
    --launch-env)
      generate_xcconfig
      export_launch_env
      ;;
    *)
      echo "usage: ensure-ios-privy-config.sh [generate|--launch-env]" >&2
      exit 1
      ;;
  esac
fi
